export const types = {
  SET_PARALLEL_RATES: "PARALLEL_MARKET_SET_PARALLEL_RATES" as "PARALLEL_MARKET_SET_PARALLEL_RATES",
  SET_BLACK_RATES: "PARALLEL_MARKET_SET_BLACK_RATES" as "PARALLEL_MARKET_SET_BLACK_RATES",
  SET_PARALLEL_ERROR: "PARALLEL_MARKET_SET_PARALLEL_ERROR" as "PARALLEL_MARKET_SET_PARALLEL_ERROR",
  SET_BLACK_ERROR: "PARALLEL_MARKET_SET_BLACK_ERROR" as "PARALLEL_MARKET_SET_BLACK_ERROR",
};
